// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocalConfig() {
  return window['go']['service']['ConfigService']['GetLocalConfig']();
}

export function InitLocalConfig() {
  return window['go']['service']['ConfigService']['InitLocalConfig']();
}
