// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';

export function GetServerStartConfig():Promise<common.ServerStartConfig>;

export function InitServerStartConfig():Promise<void>;
