// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';

export function GetLocalConfig():Promise<common.LocalConfig>;

export function InitLocalConfig():Promise<void>;
