// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServerStartConfig() {
  return window['go']['service']['ConfigService']['GetServerStartConfig']();
}

export function InitServerStartConfig() {
  return window['go']['service']['ConfigService']['InitServerStartConfig']();
}
