// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BindCtx(arg1) {
  return window['go']['service']['ConfigService']['BindCtx'](arg1);
}

export function GetServerStartConfig() {
  return window['go']['service']['ConfigService']['GetServerStartConfig']();
}

export function GetStartCommand() {
  return window['go']['service']['ConfigService']['GetStartCommand']();
}
