// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BindCtx(arg1) {
  return window['go']['service']['PathChooser']['BindCtx'](arg1);
}

export function ChooseFile() {
  return window['go']['service']['PathChooser']['ChooseFile']();
}

export function ChooseFileFolder() {
  return window['go']['service']['PathChooser']['ChooseFileFolder']();
}
