// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BindCtx(arg1) {
  return window['go']['service']['ServerManager']['BindCtx'](arg1);
}

export function CancelServer() {
  return window['go']['service']['ServerManager']['CancelServer']();
}

export function StartServer() {
  return window['go']['service']['ServerManager']['StartServer']();
}
